version: '3'

services:
  trader:
    build:
      context: .
      dockerfile: .docker/node/Dockerfile
    image: grid-bot-nodejs
    container_name: trades
    restart: unless-stopped
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-}
      - POSTGRES_DB=${POSTGRES_DB:-gridbot}
    volumes:
      - .:/home/node/app
      #- node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

  trade-watcher:
    image: grid-bot-nodejs
    container_name: trade-watcher
    restart: unless-stopped
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-gridbot}
    volumes:
      - .:/home/node/app
      #- node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes: 
      #- db:/var/lib/postgresql/data
      # use local folder to persist data
      - "${POSTGRES_PERSIST_FOLDER_OR_VOLUME:-./data}:/var/lib/postgresql/data"
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - redis:/data

volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  app-network:
    driver: bridge